2018 -01-22 17:22 :59 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000002, sdfsdf, dsfsdf, 12
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000002, sdfsdf, dsfsdf, 12
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :00 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000036, 是到底是谁的, 但是的淡淡的淡淡的淡淡的淡淡的等等的淡淡的淡淡的淡淡的淡淡的等等的的淡淡的淡淡的淡淡的淡淡的等等的的淡淡的淡淡的淡淡的淡淡的, 02
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000036, 是到底是谁的, 但是的淡淡的淡淡的淡淡的淡淡的等等的淡淡的淡淡的淡淡的淡淡的等等的的淡淡的淡淡的淡淡的淡淡的等等的的淡淡的淡淡的淡淡的淡淡的, 02
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :00 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000036, 备注信息, 子系统范围信息, 11
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000036, 备注信息, 子系统范围信息, 11
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :00 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000036, 备注信息, 范围信息, 55
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000036, 备注信息, 范围信息, 55
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :00 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000151, 1111111111111111111111111, 1111111111111111111111111111111, 01
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100000151, 1111111111111111111111111, 1111111111111111111111111111111, 01
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :00 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100001B58, 阿斯达, 按时, 22
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, 100001B58, 阿斯达, 按时, 22
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :00 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: 0310, 10000E828, 1, 1, 01
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: 0310, 10000E828, 1, 1, 01
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :00 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, LX0000008, xcvcx, cvxc, 11
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, LX0000008, xcvcx, cvxc, 11
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :01 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 撒vcbcvbcvb, cvbcvbcv, 02
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 撒vcbcvbcvb, cvbcvbcv, 02
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :01 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 存储, 222, 03
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 存储, 222, 03
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :01 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 是事实, 搜索, 06
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 是事实, 搜索, 06
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :01 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 是事实, 飒飒, 07
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 是事实, 飒飒, 07
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :01 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 65, 45, 09
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 65, 45, 09
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :01 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, asdasd, asdasd, 1111
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, asdasd, asdasd, 1111
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :02 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 22222, 222, 15
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 22222, 222, 15
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :02 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, beizhu , 020, 21
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, beizhu , 020, 21
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 26 more
2018 -01-22 17:23 :02 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 22222, 222, 22
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, 22222, 222, 22
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 25 more
2018 -01-22 17:23 :02 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, beizhu , 020, 23
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, beizhu , 020, 23
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 25 more
2018 -01-22 17:23 :02 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, sdddddf, wwwdsf, 25
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, sdddddf, wwwdsf, 25
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 25 more
2018 -01-22 17:23 :02 [ERROR] - db.sys.server.handle.impl.DefaultMysqlHandler -DefaultMysqlHandler.java(64) -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, fsdfsdfsdfsdfsdfsedfdsdfsdgvsdxcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc, 55555, 55
 org.javalite.activejdbc.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist, query: insert into imm_sub_sys_of_alarm_host  (dataFrom, devId, fMemo, subRange, subSysId) values (?,?,?,?,?) , params: site1, XJ1213002, fsdfsdfsdfsdfsdfsedfdsdfsdgvsdxcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc, 55555, 55
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.javalite.activejdbc.DB.exec(DB.java:565)
	at db.sys.server.handle.impl.DefaultMysqlHandler.handler(DefaultMysqlHandler.java:56)
	at db.sys.server.mysql.MysqlDatabase.traverse(MysqlDatabase.java:231)
	at db.sys.server.Main$1.call(Main.java:73)
	at db.sys.server.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'imm_sjz_222_tbj.imm_sub_sys_of_alarm_host' doesn't exist
	... 25 more
